
    create table league (
       id integer generated by default as identity (start with 1),
        name varchar(255),
        start_date date,
        primary key (id)
    )

    create table player (
       id integer generated by default as identity (start with 1),
        age integer not null,
        first_name varchar(255),
        last_name varchar(255),
        value double,
        team_id integer,
        primary key (id)
    )

    create table team (
       id integer generated by default as identity (start with 1),
        country varchar(255),
        good boolean,
        name varchar(255),
        league_id integer,
        primary key (id)
    )

    alter table league 
       add constraint UK_n8qcbpi2pjf8bbenfm9le3v36 unique (name)

    alter table player 
       add constraint FKdvd6ljes11r44igawmpm1mc5s 
       foreign key (team_id) 
       references team

    alter table team 
       add constraint FK9rk8716asfr76xkn99aa3uvp 
       foreign key (league_id) 
       references league
